import React,{useEffect,useState} from 'react';
import {Link,NavLink,Routes,Route,useLocation} from 'react-router-dom';
import {GraduationCap,Menu,X,MapPin,Phone,Mail,ShieldCheck,ArrowUpRight} from 'lucide-react';
import {api,img} from './api.js';
import {Home} from './Home.jsx';
import {Register} from './Register.jsx';
import {Status} from './Status.jsx';
import {Admin} from './Admin.jsx';
export const defaults={eventName:'SHREE 2026 OLYMPIAD',fee:149,registrationOpen:false,examDate:'',venue:'Shree Ram Public School, Kanhra-Badhra Road, Charkhi Dadri, Haryana 127306',paymentMode:'manual',contactPhone:'8199991081',contactEmail:'srpskanhra@gmail.com',scholarships:[]};
export function useSettings(){const [settings,setSettings]=useState(defaults);const [loading,setLoading]=useState(true);useEffect(()=>{api.get('/settings').then(r=>setSettings(r.data)).catch(()=>{}).finally(()=>setLoading(false));},[]);return {settings,loading,reload:()=>api.get('/settings').then(r=>setSettings(r.data))};}
function Header(){const [open,setOpen]=useState(false);const location=useLocation();useEffect(()=>setOpen(false),[location]);const links=[['/','Home'],['/#about','About'],['/#prizes','Prizes'],['/#scholarship','Scholarships'],['/status','Check Status']];return <header className="header"><div className="shell head-row"><Link to="/" className="brand"><img src={img('school-logo.png')} alt="School crest"/><span>SHREE RAM <b>PUBLIC SCHOOL</b><small>LEARN <i>|</i> GROW <i>|</i> ACHIEVE</small></span></Link><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'}>{links.map(([url,label])=><a key={url} href={url}>{label}</a>)}<NavLink className="nav-register" to="/register">Register Now <ArrowUpRight size={16}/></NavLink></nav></div></header>}
function Footer({settings}){return <footer className="footer"><div className="shell footer-grid"><div><div className="footer-brand"><img src={img('school-logo.png')} alt="School crest"/><strong>SHREE RAM<br/>PUBLIC SCHOOL</strong></div><p>Where Talent Meets Opportunity. Identifying potential and celebrating academic growth.</p><span className="since">SINCE 2012 · LEARN | GROW | ACHIEVE</span></div><div><h4>QUICK LINKS</h4><Link to="/register">Online Registration</Link><Link to="/status">Check Status / Admit Card</Link><Link to="/admin">Admin Login</Link><a href="https://www.srpskanhra.com/" target="_blank" rel="noreferrer">School Website</a></div><div><h4>CONTACT THE SCHOOL</h4><p><MapPin size={16}/>Kanhra-Badhra Road, Charkhi Dadri, Haryana 127306</p><p><Phone size={16}/>{settings.contactPhone}</p><p><Mail size={16}/>{settings.contactEmail}</p></div></div><div className="shell copyright">© 2026 Shree Ram Public School · Olympiad portal</div></footer>}
export default function App(){const {settings,loading}=useSettings();return <><Header/><Routes><Route path="/" element={<Home settings={settings}/>}/><Route path="/register" element={<Register settings={settings} loading={loading}/>}/><Route path="/status" element={<Status/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<main className="shell empty"><h1>Page not found</h1><Link className="btn primary" to="/">Back home</Link></main>}/></Routes><Footer settings={settings}/></>}
