import React from 'react';
import {Link} from 'react-router-dom';
import './school-pages.css';
export function ExtraPage({kind,settings}){const guide=kind==='guide';return <main className="school-page"><section className="school-page-hero shell"><div><span className="school-page-eyebrow">SHREE 2026 OLYMPIAD</span><h1>{guide?'Prepare with confidence.':'A little help. A clear next step.'}</h1><p>{guide?'Plan your preparation, keep your application details ready and check the school’s confirmed examination instructions.':'Find answers about registration, payment review and accessing your student documents.'}</p><Link className="btn gold" to="/register">Registration details →</Link></div><div className="school-page-hero-art"><img src={guide?'/images/srps-mathematics.png':'/images/srps-registration.png'} alt={guide?'Students exploring mathematics':'Student using online school services'}/></div></section><section className="shell school-page-section"><h2>{guide?'Your exam preparation checklist':'Frequently asked questions'}</h2>{(guide?[
['Start with your class','Revise concepts from your current class. Use your school notes and textbooks to practise understanding rather than memorising answers.'],['Build a steady routine','Set aside a regular study period. Mix revision with practice questions and review the questions you find difficult.'],['Confirm the exam pattern','Ask the school for the confirmed syllabus, subjects, duration and marking scheme. The website’s subject illustrations are an introduction, not an official syllabus.'],['Check your exam details',`Published exam date: ${settings.examDate||'To be announced'}. Confirm reporting time and venue using your issued admit card and school instructions.`],['Before exam day','Keep your admit card ready after payment approval. Ask the school which identification, stationery and other materials you should bring.']]:[
['Who can register?','The programme welcomes students in Classes 1–12. Enter the student’s current class and accurate details.'],['Which mobile number should I use?','Use the guardian mobile number you can access for OTP verification. Keep that number available for future status checks.'],['What is the registration fee?',`The current registration fee is ₹${settings.fee}. Follow the payment details displayed in the registration flow.`],['Does uploading a receipt confirm payment?','No. A submitted payment receipt must be reviewed. Check your application status for the latest confirmation.'],['Why can I only download an application receipt?','An application receipt acknowledges your submission. The admit card becomes available after payment confirmation.'],['What if my details are incorrect?','Contact the school with your application reference and explain the correction required. Never share your OTP.'],['How do I confirm prize and scholarship eligibility?','Contact the school for final award rules, scholarship coverage and duration. Promotional illustrations show categories, not guaranteed individual awards.']]).map(([title,copy])=><article className="content-expansion-item" key={title}><h3>{title}</h3><p>{copy}</p></article>)}</section><section className="school-page-end shell"><div><h2>Need help from the school?</h2><p>Keep your application reference ready when contacting the office.</p><a href={`tel:${settings.contactPhone}`}>{settings.contactPhone}</a><p><a href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a></p></div><Link className="btn gold" to="/status">Check application status →</Link></section></main>;}
const additions={
'/': ['A clear path from curiosity to exam day',[['Explore the programme','Browse prize categories, scholarship opportunities and the preparation guide before starting your application.'],['Keep your details ready','Have the student’s school details, date of birth, address, guardian mobile and a clear photograph ready.'],['Stay informed','Save your application reference and revisit Check Status after school payment review.']]],
'/about':['Working together for student confidence',[['For students','Approach the Olympiad as an opportunity to learn, reflect and discover areas you enjoy.'],['For families','Help your child submit accurate details, keep the registered mobile accessible and follow school updates.'],['Our school community','Learning is supported by shared effort between students, guardians and the school team.']]],
'/prizes':['Recognition starts with participation',[['Find your category','Check the class group associated with each prize category. Ask the school about final selection and distribution.'],['Illustrations and actual awards','Product images are illustrative. Exact models and award conditions are confirmed by the school.'],['Explore more opportunities','Scholarship opportunities are listed separately. Review their criteria as well as prize information.']]],
'/scholarships':['Questions to discuss with the school',[['What is covered?','Confirm which fees or educational costs the scholarship applies to.'],['How long does it apply?','Ask about the benefit period, renewal conditions and any required documents.'],['What happens after results?','Contact the school to confirm your applicable slab and the steps to claim an eligible benefit.']]],
'/register':['Before you submit your application',[['Review student details','Check spelling, class, date of birth and school details before continuing.'],['Keep your reference','Save the application receipt and reference for future status checks.'],['Payment review','Use the payment instructions in the form. A receipt upload is followed by verification.']]],
'/status':['Understand your documents',[['Application receipt','Your acknowledgement of submission. Keep it for the application reference and follow-up.'],['Payment status','The latest recorded payment review status. Contact the school if you need clarification.'],['Admit card','Available after payment confirmation. Review its student and examination details before exam day.']]],
};
export function PageMoreContent({pathname}){const data=additions[pathname];if(!data)return null;return <section className="page-more-content"><div className="shell"><span className="school-page-eyebrow">GOOD TO KNOW</span><h2>{data[0]}</h2><div className="page-more-grid">{data[1].map(([title,copy])=><article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><div className="page-more-links"><Link to="/exam-guide">Explore the exam guide →</Link><Link to="/help">FAQs & help →</Link></div></div></section>;}
