import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Calculator, FlaskConical, Globe2, Lightbulb, Trophy, ShieldCheck, FileText, IndianRupee, Download, CalendarDays, GraduationCap, Laptop, Tablet, Bike, Watch, Check, Plus, Phone, MapPin } from 'lucide-react';
import './home-redesign.css';
import {ScholarshipShowcase} from './ScholarshipShowcase.jsx';
import {OriginalHero} from './OriginalHero.jsx';
import {SubjectCarousel} from './SubjectCarousel.jsx';
import {RegistrationJourney} from './RegistrationJourney.jsx';
const subjects = [[Calculator,'Mathematics','Think logically. Solve confidently.'],[FlaskConical,'Science','Ask questions. Explore possibilities.'],[BookOpen,'English','Read, understand and express.'],[Globe2,'Social Science','Understand the world around you.'],[Lightbulb,'General Awareness','Stay curious. Keep discovering.']];
const steps = [[FileText,'Fill your application','Add student details and your guardian’s mobile number.'],[ShieldCheck,'Verify & upload','Verify your mobile by OTP and upload a clear photograph.'],[IndianRupee,'Complete payment','Pay the registration fee and submit the required payment details.'],[Download,'Get exam-ready','Download your admit card once payment is confirmed.']];
const awards = [[Laptop,'Classes 9–12','Laptop'],[Tablet,'Classes 6–8','Tablet'],[Bike,'Classes 1–5','Bicycle'],[Watch,'Eligible participants','Watch']];
function Heading({eyebrow,title,copy}) {return <div className="shree-section-heading"><span className="shree-eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</div>;}
export function Home({settings}) {
 const faqs=[['Who can participate?','The Olympiad is open to students from Classes 1 to 12. Enter your current class and accurate school details in the registration form.'],['How much is the registration fee?',`The registration fee is ₹${settings.fee}. Use only the payment details shown in the registration portal.`],['When can I download my admit card?','Your admit card becomes available after payment confirmation. Open Check Status, enter your application reference and guardian mobile number, and verify the OTP.'],['What should I keep after registration?','Save your application reference and application receipt. You will need the reference and registered guardian mobile to check your application later.'],['How are prizes and scholarships awarded?','The categories and scholarship slabs shown are subject to the school’s final eligibility, coverage and award rules. Contact the school office for confirmation.']];
 return <main className="shree-home">
  <OriginalHero settings={settings}/>
  <div className="shree-announcement"><div className="shell"><span><CalendarDays/>Exam date <b>{settings.examDate || 'To be announced'}</b></span><span><IndianRupee/>Registration fee <b>₹{settings.fee}</b></span><span><ShieldCheck/><b>{settings.registrationOpen?'Registrations open':'Registration updates coming soon'}</b></span></div></div>
  <section className="shree-about shell" id="about"><div><span className="shree-eyebrow">MORE THAN AN EXAM</span><h2>A little curiosity.<br/>A <em>lot of potential.</em></h2></div><div><p>At Shree Ram Public School, we believe learning begins with asking questions. SHREE 2026 OLYMPIAD gives students a chance to explore their strengths, build academic confidence and enjoy a healthy challenge.</p><a className="shree-text-link" href="#how-to-register">Find your starting point <ArrowUpRight size={18}/></a></div></section>
  <section className="shree-subjects shell"><Heading eyebrow="FIVE WAYS TO DISCOVER YOUR STRENGTH" title="Curious minds belong here."/><SubjectCarousel/><div className="shree-subject-grid">{subjects.map(([Icon,title,copy],i)=><article key={title}><span className="shree-subject-index">0{i+1}</span><div className="shree-subject-icon"><Icon size={31}/></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="shree-awards" id="prizes"><div className="shell"><Heading eyebrow="EFFORT DESERVES RECOGNITION" title={<>Dream big. Give it your best.</>} copy="Explore the prize categories in our school’s Olympiad programme."/><div className="shree-discovery-art"><img src="/images/srps-rewards.png" alt="Colourful prize illustration featuring a golden trophy, laptop, tablet, bicycle and smartwatch" width="1536" height="1024" loading="lazy" decoding="async"/></div><div className="shree-award-grid">{awards.map(([Icon,group,title],i)=><article key={title}><div className="shree-award-visual"><span>0{i+1}</span><img src={`/images/prize-${title === 'Watch' ? 'smartwatch' : title.toLowerCase()}.png`} alt={`${title === 'Watch' ? 'Smartwatch' : title} prize illustration`} width="1024" height="1024" loading="lazy" decoding="async"/></div><span className="shree-award-group">{group}</span><h3>{title}</h3></article>)}</div><p className="shree-fineprint">Prize categories are based on the school’s promotional programme. Final eligibility and award rules are confirmed by the school.</p></div></section>
  <ScholarshipShowcase settings={settings}/>
  <RegistrationJourney settings={settings}/>
  <section className="shree-exam shell"><div className="shree-exam-heading"><span className="shree-eyebrow">MARK YOUR CALENDAR</span><h2>Your next challenge<br/>starts here.</h2><p>Keep your application reference safe. After payment approval, your admit card will include your exam details.</p><Link className="shree-text-link" to="/status">Check status & download admit card <ArrowUpRight size={18}/></Link></div><div className="shree-exam-info">{[[CalendarDays,'EXAM DATE',settings.examDate || 'To be announced'],[MapPin,'EXAM VENUE',settings.venue || 'Shree Ram Public School'],[IndianRupee,'REGISTRATION FEE',`₹${settings.fee}`],[Phone,'NEED A HAND?',settings.contactPhone]].map(([Icon,label,value])=><div key={label}><Icon/><span><small>{label}</small><strong>{value}</strong></span></div>)}</div></section>
  <section className="shree-faq shell"><Heading eyebrow="A LITTLE CLARITY BEFORE YOU BEGIN" title="Good questions. Clear answers."/><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<Plus size={20}/></summary><p>{answer}</p></details>)}</div></section>
  <section className="shree-final-cta"><div className="shell"><div><span className="shree-eyebrow">SHREE 2026 OLYMPIAD</span><h2>Ready to discover<br/>what you can do?</h2><p>Your curiosity. Your effort. Your next achievement.</p></div><Link className="shree-button" to="/register">Let’s get started <ArrowUpRight size={22}/></Link><GraduationCap className="shree-cta-art" aria-hidden="true"/></div></section>
 </main>;
}
function Sparkle(){return <span aria-hidden="true">✦</span>;}
function StarShape(){return <span className="shree-award-star" aria-hidden="true">✦</span>;}
