import {StudentArtwork} from './StudentArtwork.jsx';
import {eligibleClassLabel} from './publicDisplay.js';
import {formatPublicDate} from './publicDisplay.js';
import React from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight, BookOpen, Trophy, GraduationCap, ShieldCheck, Phone, MapPin, Check} from 'lucide-react';
import {RegistrationJourney} from './RegistrationJourney.jsx';
import './school-pages.css';
import {eventBrand,prizeCategories} from './portalData.js';

function PageHero({eyebrow,title,copy,image,alt}) {
 return <section className="school-page-hero shell"><div><nav aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><span>{eyebrow}</span></nav><span className="school-page-eyebrow">SHREE RAM PUBLIC SCHOOL</span><h1>{title}</h1><p>{copy}</p><Link className="btn gold" to="/register">Explore registration <ArrowUpRight size={18}/></Link></div><div className="school-page-hero-art"><img src={image} alt={alt} fetchpriority="high"/></div></section>;
}
function PageEnd({settings}) {return <section className="school-page-end shell"><div><span className="school-page-eyebrow">YOUR NEXT CHAPTER</span><h2>Bring your curiosity.<br/>Take the next step.</h2><p>Exam date: {formatPublicDate(settings.examDate)} · Registration fee: ₹{settings.fee}</p></div><div><Link className="btn gold" to="/register">{settings.registrationOpen?'Register now':'Registration details'} <ArrowUpRight size={18}/></Link><Link to="/status">Already applied? Check status →</Link></div></section>;}
export function AboutPage({settings}) {return <main className="school-page">
 <PageHero eyebrow="About" title={<>Small steps.<br/><em>Bright futures.</em></>} copy={`Discover ${eventBrand(settings).eventName}, an academic opportunity from Shree Ram Public School for students in Classes ${eligibleClassLabel(settings)} to explore their strengths and build confidence.`} image="/images/srps-awareness.png" alt="Illustration of students discovering science, books and the world"/>
 <section className="school-page-story shell"><div><span className="school-page-eyebrow">A SCHOOL. A COMMUNITY. A SHARED AMBITION.</span><h2>Learning goes<br/>beyond the classroom.</h2><p>Our Olympiad brings curiosity, preparation and healthy competition together. It encourages students to think independently, discover new interests and take pride in their effort.</p><p>Shree Ram Public School is based in Kanhra, Charkhi Dadri, Haryana. The school team supports families through registration, payment review and admit-card access.</p></div><figure><img src="/images/school-community.png" alt="School community group photograph supplied by Shree Ram Public School" loading="lazy"/><figcaption>Moments from our school community.</figcaption></figure></section>
 <StudentArtwork type="welcome" className="shell student-section-artwork"/><section className="school-page-values shell">{[[BookOpen,'Curiosity','Ask questions, explore ideas and build understanding.'],[Trophy,'Confidence','Prepare with purpose and give your best effort.'],[GraduationCap,'Opportunity','Explore recognition and scholarship opportunities.']].map(([Icon,title,copy])=><article key={title}><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</section>
 <RegistrationJourney settings={settings}/><section className="school-page-contact shell"><div><MapPin/><h3>Visit the school</h3><p>{settings.venue}</p></div><div><Phone/><h3>Talk to our team</h3><a href={`tel:${settings.contactPhone}`}>{settings.contactPhone}</a><p><a href={`mailto:${settings.contactEmail}`}>{settings.contactEmail}</a></p></div></section><PageEnd settings={settings}/>
 </main>;}
export function PrizesPage({settings}) {const prizes=prizeCategories;return <main className="school-page">
 <PageHero eyebrow="Prizes" title={<>Big dreams.<br/><em>Exciting rewards.</em></>} copy={`Celebrate ambition and academic effort. Discover the prize categories in the ${eventBrand(settings).eventName} programme.`} image="/images/srps-rewards.png" alt="Students in school uniform exploring Olympiad prize categories"/>
 <section className="shell school-page-section"><span className="school-page-eyebrow">SOMETHING TO AIM FOR</span><h2>Find your prize category.</h2><div className="school-prize-cards">{prizes.map(({image,eligibleClasses:group,name:title,description:copy})=><article key={title}><img src={image} alt={`${title} prize illustration`} loading="lazy"/><div><small>{group}</small><h3>{title}</h3><p>{copy}</p></div></article>)}</div><p className="school-page-note">Images illustrate prize categories. Final models, selection criteria and participation award eligibility are confirmed by the school.</p></section>
 <StudentArtwork type="awards" className="shell student-section-artwork"/><section className="school-page-rule shell"><ShieldCheck/><div><h2>Award information</h2><Link to="/awards">View Award Rules →</Link><p>Class categories follow the school’s promotional programme. Contact the school for final prize allocation and eligibility before relying on an award. Submitting an application does not confirm a competitive prize.</p><Link to="/scholarships">Explore scholarship opportunities <ArrowUpRight size={16}/></Link></div></section><PageEnd settings={settings}/></main>;}
export function ScholarshipsPage({settings,loading,settingsError,reloadSettings}) {return <main className="school-page">
 <PageHero eyebrow="Scholarships" title={<>Your effort.<br/><em>More possibilities.</em></>} copy="Explore scholarship opportunities based on Olympiad performance. Take a confident step towards learning with Shree Ram Public School." image="/images/srps-scholarships.png" alt="Students discovering new ideas through books and learning"/>
 <section className="school-page-story shell"><div><span className="school-page-eyebrow">PERFORMANCE MEETS OPPORTUNITY</span><h2>Make your learning count.</h2><p>The scholarship slabs below come from the school’s current programme settings. The school confirms eligibility, coverage and duration.</p><ul className="school-page-checks"><li><Check/>Participate in the Olympiad</li><li><Check/>Receive your performance outcome</li><li><Check/>Confirm applicable benefits with the school</li></ul></div><div className="school-benefits"><h3><GraduationCap/>Scholarship opportunities</h3>{loading?<p role="status">Loading scholarship details…</p>:settingsError?<div role="alert"><p>Unable to load scholarship details. Please try again.</p><button className="btn outlined-dark" onClick={reloadSettings}>Retry</button></div>:(settings.scholarships || []).length?<table><caption>Performance and proposed scholarship benefit</caption><thead><tr><th scope="col">Olympiad marks</th><th scope="col">Benefit</th></tr></thead><tbody>{settings.scholarships.map((s,i)=><tr key={i}><td>{s.marks}</td><td>{s.benefit} scholarship</td></tr>)}</tbody></table>:<p>Scholarship details for {eventBrand(settings).eventName} will be announced shortly.</p>}</div></section>
 <StudentArtwork type="awards" className="shell student-section-artwork"/><section className="school-page-rule shell"><ShieldCheck/><div><h2>Know the details before you apply.</h2><p>Scholarship percentages do not by themselves specify the fees covered or the benefit period. Please ask the school to confirm coverage, duration and any additional conditions.</p><a href={`tel:${settings.contactPhone}`}>Speak with the school: {settings.contactPhone}</a></div></section><PageEnd settings={settings}/></main>;}
