import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Search,ShieldCheck,Download,CheckCircle2,Clock3} from 'lucide-react';
import {api,downloadBlob,img} from './api.js';
export function Status(){const [ref,setRef]=useState(''),[phone,setPhone]=useState(''),[code,setCode]=useState(''),[lookupToken,setLookupToken]=useState(''),[access,setAccess]=useState(''),[record,setRecord]=useState(null),[devOtp,setDevOtp]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function run(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function request(){run(async()=>{const r=await api.post('/status/request',{registrationNumber:ref.trim().toUpperCase(),phone});setLookupToken(r.data.lookupToken);setDevOtp(r.data.devOtp||'');});}
 function verify(){run(async()=>{const r=await api.post('/status/verify',{otp:code},{headers:{Authorization:`Bearer ${lookupToken}`}});setAccess(r.data.accessToken);setRecord(r.data.registration);});}
 function download(){run(async()=>{const r=await api.get('/admit-card',{headers:{Authorization:`Bearer ${access}`},responseType:'blob'});downloadBlob(r.data,`${record.registrationNumber}.pdf`);});}
 return <main className="status-page shell"><div className="page-intro"><span className="eyebrow">STUDENT SERVICES</span><h1>Check status & download admit card</h1><p>Verify your guardian mobile to access private student information.</p></div><div className="status-grid"><div className="status-card">{error&&<div className="error">{error}</div>}{!lookupToken?<><div className="form-head"><Search/><div><h2>Find your application</h2><p>Enter your application reference or confirmed registration number.</p></div></div><label><span>Application reference / Registration number</span><input value={ref} onChange={e=>setRef(e.target.value)} placeholder="APP-XXXXXXXXXX or SHREE26-000001"/></label><label><span>Guardian mobile number</span><input type="tel" inputMode="numeric" value={phone} maxLength="10" onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} placeholder="10-digit registered mobile"/></label><button className="btn primary wide" disabled={busy||phone.length!==10||!ref} onClick={request}>Send secure OTP</button></>:!access?<><div className="form-head"><ShieldCheck/><div><h2>Confirm your mobile</h2><p>Enter the OTP sent to your registered phone.</p></div></div>{devOtp&&<div className="dev-code">Local test OTP: <b>{devOtp}</b></div>}<label><span>Six-digit verification code</span><input inputMode="numeric" maxLength="6" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} placeholder="000000"/></label><button className="btn primary wide" disabled={busy||code.length!==6} onClick={verify}>Verify & view status</button></>:<><div className="form-head"><CheckCircle2/><div><h2>Application details</h2><p>Your mobile number is verified.</p></div></div><div className="receipt-summary">{[['Student',record.studentName],['Class',record.studentClass],['Application ref.',record.applicationRef],['Registration no.',record.registrationNumber||'Pending'],['Status',record.status.replaceAll('_',' ')],['Room',record.room||'To be assigned'],['Seat',record.seat||'To be assigned']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>{record.status==='CONFIRMED'?<button className="btn primary wide" disabled={busy} onClick={download}><Download size={17}/> Download admit card PDF</button>:<div className="notice"><Clock3 size={16}/> Admit card will be available after payment verification by the school.</div>}</> }<p className="hint">Need help? Contact the school office. Never share your OTP.</p></div><div className="status-image"><img src={img('admit.webp')} alt="Admit card download illustration"/></div></div><div className="center-link"><Link to="/register" className="btn outlined-dark">New registration</Link></div></main>;
}
